/Users/alexmorse/.vim/after/syntax/cpp.vim
/Users/alexmorse/.vim/after/syntax/html.vim
/Users/alexmorse/.vim/autoload/pathogen.vim
/Users/alexmorse/.vim/bundle/ag/autoload/ag.vim
/Users/alexmorse/.vim/bundle/ag/doc/ag.txt
/Users/alexmorse/.vim/bundle/ag/plugin/ag.vim
/Users/alexmorse/.vim/bundle/ag/Rakefile
/Users/alexmorse/.vim/bundle/ag/README.md
/Users/alexmorse/.vim/bundle/clang/autoload/getopts/cache.vim
/Users/alexmorse/.vim/bundle/clang/autoload/getopts/clang.vim
/Users/alexmorse/.vim/bundle/clang/autoload/getopts/cpp.clang.cache
/Users/alexmorse/.vim/bundle/clang/autoload/getopts/gcc.vim
/Users/alexmorse/.vim/bundle/clang/autoload/snippets/clang_complete.vim
/Users/alexmorse/.vim/bundle/clang/autoload/snippets/dummy.vim
/Users/alexmorse/.vim/bundle/clang/autoload/snippets/snipmate.vim
/Users/alexmorse/.vim/bundle/clang/autoload/snippets/ultisnips.vim
/Users/alexmorse/.vim/bundle/clang/bin/cc_args.py
/Users/alexmorse/.vim/bundle/clang/doc/clang_complete.txt
/Users/alexmorse/.vim/bundle/clang/examples/boost.cpp
/Users/alexmorse/.vim/bundle/clang/Makefile
/Users/alexmorse/.vim/bundle/clang/plugin/clang/__init__.py
/Users/alexmorse/.vim/bundle/clang/plugin/clang/cindex.py
/Users/alexmorse/.vim/bundle/clang/plugin/clang_complete.vim
/Users/alexmorse/.vim/bundle/clang/plugin/libclang.py
/Users/alexmorse/.vim/bundle/clang/README
/Users/alexmorse/.vim/bundle/command-t/command-t.gemspec
/Users/alexmorse/.vim/bundle/command-t/compile-test.sh
/Users/alexmorse/.vim/bundle/command-t/doc/command-t.txt
/Users/alexmorse/.vim/bundle/command-t/fixtures/bar/abc
/Users/alexmorse/.vim/bundle/command-t/fixtures/bar/xyz
/Users/alexmorse/.vim/bundle/command-t/fixtures/baz
/Users/alexmorse/.vim/bundle/command-t/fixtures/bing
/Users/alexmorse/.vim/bundle/command-t/fixtures/foo/alpha/t1
/Users/alexmorse/.vim/bundle/command-t/fixtures/foo/alpha/t2
/Users/alexmorse/.vim/bundle/command-t/fixtures/foo/beta
/Users/alexmorse/.vim/bundle/command-t/Gemfile
/Users/alexmorse/.vim/bundle/command-t/Gemfile.lock
/Users/alexmorse/.vim/bundle/command-t/LICENSE
/Users/alexmorse/.vim/bundle/command-t/Makefile
/Users/alexmorse/.vim/bundle/command-t/multi-spec.sh
/Users/alexmorse/.vim/bundle/command-t/plugin/command-t.vim
/Users/alexmorse/.vim/bundle/command-t/Rakefile
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/controller.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/depend
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/ext.bundle
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/ext.c
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/ext.h
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/ext.o
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/extconf.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/finder/buffer_finder.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/finder/file_finder.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/finder/jump_finder.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/finder/tag_finder.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/finder.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/Makefile
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/match.c
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/match.h
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/match.o
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/match_window.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/matcher.c
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/matcher.h
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/matcher.o
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/prompt.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/ruby_compat.h
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/scanner/buffer_scanner.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/scanner/file_scanner.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/scanner/jump_scanner.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/scanner/tag_scanner.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/scanner.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/settings.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/stub.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/vim/path_utilities.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/vim/screen.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/vim/window.rb
/Users/alexmorse/.vim/bundle/command-t/ruby/command-t/vim.rb
/Users/alexmorse/.vim/bundle/command-t/spec/command-t/controller_spec.rb
/Users/alexmorse/.vim/bundle/command-t/spec/command-t/finder/buffer_finder_spec.rb
/Users/alexmorse/.vim/bundle/command-t/spec/command-t/finder/file_finder_spec.rb
/Users/alexmorse/.vim/bundle/command-t/spec/command-t/match_spec.rb
/Users/alexmorse/.vim/bundle/command-t/spec/command-t/matcher_spec.rb
/Users/alexmorse/.vim/bundle/command-t/spec/command-t/scanner/buffer_scanner_spec.rb
/Users/alexmorse/.vim/bundle/command-t/spec/command-t/scanner/file_scanner_spec.rb
/Users/alexmorse/.vim/bundle/command-t/spec/spec_helper.rb
/Users/alexmorse/.vim/bundle/command-t/spec/vim_formatter.rb
/Users/alexmorse/.vim/bundle/fugitive/doc/fugitive.txt
/Users/alexmorse/.vim/bundle/fugitive/plugin/fugitive.vim
/Users/alexmorse/.vim/bundle/fugitive/README.markdown
/Users/alexmorse/.vim/bundle/html5syntax/README.markdown
/Users/alexmorse/.vim/bundle/html5syntax/syntax/html/aria.vim
/Users/alexmorse/.vim/bundle/html5syntax/syntax/html/html5.vim
/Users/alexmorse/.vim/bundle/html5syntax/syntax/html/rdfa.vim
/Users/alexmorse/.vim/bundle/minbufexpl/doc/minibufexpl.txt
/Users/alexmorse/.vim/bundle/minbufexpl/plugin/minibufexpl.vim
/Users/alexmorse/.vim/bundle/minbufexpl/project.html
/Users/alexmorse/.vim/bundle/minbufexpl/readme.markdown
/Users/alexmorse/.vim/bundle/nerdcommenter/doc/NERD_commenter.txt
/Users/alexmorse/.vim/bundle/nerdcommenter/plugin/NERD_commenter.vim
/Users/alexmorse/.vim/bundle/nerdcommenter/Rakefile
/Users/alexmorse/.vim/bundle/nerdcommenter/README.md
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl/Colorscheme.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl/Hi.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl/Match.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl/Mod.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl/Parser.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl/Segment.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl/Theme.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Pl.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Colorschemes/default.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Functions/cfi.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Functions/ft_man.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Functions/fugitive.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Functions/syntastic.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Functions.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Matches.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments/cfi.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments/ctrlp.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments/ft_man.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments/fugitive.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments/rvm.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments/syntastic.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments/virtualenv.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Segments.vim
/Users/alexmorse/.vim/bundle/powerline/autoload/Powerline/Themes/default.vim
/Users/alexmorse/.vim/bundle/powerline/doc/Powerline.txt
/Users/alexmorse/.vim/bundle/powerline/fontpatcher/fontpatcher
/Users/alexmorse/.vim/bundle/powerline/fontpatcher/PowerlineSymbols.sfd
/Users/alexmorse/.vim/bundle/powerline/fontpatcher/README.rst
/Users/alexmorse/.vim/bundle/powerline/plugin/Powerline.vim
/Users/alexmorse/.vim/bundle/powerline/Powerline_default_default_compatible.cache
/Users/alexmorse/.vim/bundle/powerline/Powerline_default_default_fancy.cache
/Users/alexmorse/.vim/bundle/powerline/README.rst
/Users/alexmorse/.vim/bundle/relops/after/plugin/relops.vim
/Users/alexmorse/.vim/bundle/relops/doc/relops.txt
/Users/alexmorse/.vim/bundle/relops/plugin/relops.vim
/Users/alexmorse/.vim/bundle/sbd/doc/sbd.txt
/Users/alexmorse/.vim/bundle/sbd/plugin/sbd.vim
/Users/alexmorse/.vim/bundle/sbd/README.md
/Users/alexmorse/.vim/bundle/syntastic/_assets/screenshot_1.png
/Users/alexmorse/.vim/bundle/syntastic/autoload/syntastic/c.vim
/Users/alexmorse/.vim/bundle/syntastic/doc/syntastic.txt
/Users/alexmorse/.vim/bundle/syntastic/plugin/syntastic.vim
/Users/alexmorse/.vim/bundle/syntastic/README.markdown
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/applescript.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/c.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/coffee.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/cpp.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/css.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/cucumber.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/cuda.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/docbk.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/efm_perl.pl
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/erlang.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/erlang_check_file.erl
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/eruby.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/fortran.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/gentoo_metadata.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/go/6g.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/go/go.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/go/gofmt.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/go.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/haml.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/haskell.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/haxe.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/html.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/javascript/gjslint.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/javascript/jshint.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/javascript/jsl.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/javascript/jslint.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/javascript.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/json/jsonlint.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/json/jsonval.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/json.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/less.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/lua.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/matlab.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/nasm.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/ocaml.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/perl.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/php.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/puppet.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/python/flake8.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/python/pyflakes.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/python/pylint.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/python.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/rst.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/ruby/jruby.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/ruby/mri.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/ruby.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/rust.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/sass.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/scala.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/scss.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/sh.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/tcl.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/tex.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/vala.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/xhtml.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/xml.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/xslt.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/yaml.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/z80.vim
/Users/alexmorse/.vim/bundle/syntastic/syntax_checkers/zpt.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/converter_default.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/converter_file_directory.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/converter_nothing.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/converter_relative_abbr.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/converter_relative_word.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/converter_tail.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/matcher_context.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/matcher_default.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/matcher_fuzzy.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/matcher_glob.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/matcher_hide_hidden_files.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/matcher_migemo.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/matcher_regexp.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/sorter_default.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/sorter_length.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/sorter_nothing.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/sorter_rank.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/sorter_reverse.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters/sorter_word.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/filters.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/buffer.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/cdable.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/command.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/common.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/completion.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/directory.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/file.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/guicmd.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/jump_list.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/openable.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/source.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/tab.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/uri.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/window.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/kinds/word.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/mappings.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/action.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/alias.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/bookmark.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/buffer.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/change.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/command.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/directory.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/file.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/file_point.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/file_rec.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/find.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/function.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/grep.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/history_input.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/history_yank.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/jump.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/jump_point.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/launcher.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/line.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/mapping.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/menu.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/mru.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/output.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/process.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/register.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/resume.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/runtimepath.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/source.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/tab.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/vimgrep.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/sources/window.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/util.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite/vital.vim
/Users/alexmorse/.vim/bundle/unite/autoload/unite.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/_dbf7878/data/list.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/_dbf7878/data/string.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/_dbf7878/prelude.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/_dbf7878/system/cache.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/_dbf7878/system/file.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/_dbf7878/vim/buffer/manager.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/_dbf7878.vim
/Users/alexmorse/.vim/bundle/unite/autoload/vital/unite.vim.vital
/Users/alexmorse/.vim/bundle/unite/autoload/vital.vim
/Users/alexmorse/.vim/bundle/unite/doc/unite.txt
/Users/alexmorse/.vim/bundle/unite/plugin/unite/bookmark.vim
/Users/alexmorse/.vim/bundle/unite/plugin/unite/buffer.vim
/Users/alexmorse/.vim/bundle/unite/plugin/unite/history_yank.vim
/Users/alexmorse/.vim/bundle/unite/plugin/unite/mru.vim
/Users/alexmorse/.vim/bundle/unite/plugin/unite/window.vim
/Users/alexmorse/.vim/bundle/unite/plugin/unite.vim
/Users/alexmorse/.vim/bundle/unite/README.md
/Users/alexmorse/.vim/bundle/unite/syntax/unite.vim
/Users/alexmorse/.vim/bundle/unite/vest/test-matcher.vim
/Users/alexmorse/.vim/bundle/unite/vest/test-source.vim
/Users/alexmorse/.vim/bundle/vimproc/autoload/fakepoll.h
/Users/alexmorse/.vim/bundle/vimproc/autoload/proc.c
/Users/alexmorse/.vim/bundle/vimproc/autoload/proc_w32.c
/Users/alexmorse/.vim/bundle/vimproc/autoload/ptytty.c
/Users/alexmorse/.vim/bundle/vimproc/autoload/vimproc/filepath.vim
/Users/alexmorse/.vim/bundle/vimproc/autoload/vimproc/lexer.vim
/Users/alexmorse/.vim/bundle/vimproc/autoload/vimproc/parser.vim
/Users/alexmorse/.vim/bundle/vimproc/autoload/vimproc/util.vim
/Users/alexmorse/.vim/bundle/vimproc/autoload/vimproc.vim
/Users/alexmorse/.vim/bundle/vimproc/autoload/vimproc_mac.so
/Users/alexmorse/.vim/bundle/vimproc/autoload/vimstack.c
/Users/alexmorse/.vim/bundle/vimproc/doc/vimproc.txt
/Users/alexmorse/.vim/bundle/vimproc/make_android.mak
/Users/alexmorse/.vim/bundle/vimproc/make_cygwin.mak
/Users/alexmorse/.vim/bundle/vimproc/make_mac.mak
/Users/alexmorse/.vim/bundle/vimproc/make_mingw32.mak
/Users/alexmorse/.vim/bundle/vimproc/make_mingw64.mak
/Users/alexmorse/.vim/bundle/vimproc/Make_msvc.mak
/Users/alexmorse/.vim/bundle/vimproc/make_msvc32.mak
/Users/alexmorse/.vim/bundle/vimproc/make_msvc64.mak
/Users/alexmorse/.vim/bundle/vimproc/make_sunos.mak
/Users/alexmorse/.vim/bundle/vimproc/make_unix.mak
/Users/alexmorse/.vim/bundle/vimproc/plugin/vimproc.vim
/Users/alexmorse/.vim/bundle/vimproc/README.mkd
/Users/alexmorse/.vim/bundle/vimproc/tools/leak_check.vim
/Users/alexmorse/.vim/bundle/vimproc/vest/test-fopen.vim
/Users/alexmorse/.vim/bundle/vimproc/vest/test-functions.vim
/Users/alexmorse/.vim/bundle/vimproc/vest/test-lexer.vim
/Users/alexmorse/.vim/bundle/vimproc/vest/test-parser.vim
/Users/alexmorse/.vim/bundle/vimproc/vest/test-popen.vim
/Users/alexmorse/.vim/bundle/vimproc/vest/test-socket.vim
/Users/alexmorse/.vim/bundle/vimproc/vest/test-system.vim
/Users/alexmorse/.vim/colors/blackdust.vim
/Users/alexmorse/.vim/colors/desertedocean.vim
/Users/alexmorse/.vim/colors/freya.vim
/Users/alexmorse/.vim/colors/ir_black.vim
/Users/alexmorse/.vim/colors/molokai.vim
/Users/alexmorse/.vim/colors/monokai.vim
/Users/alexmorse/.vim/colors/python.vim
/Users/alexmorse/.vim/colors/symfony.vim
/Users/alexmorse/.vim/colors/Tomorrow-Night-Bright.vim
/Users/alexmorse/.vim/colors/Tomorrow-Night-Eighties.vim
/Users/alexmorse/.vim/colors/Tomorrow-Night.vim
/Users/alexmorse/.vim/colors/vanzan_color.vim
/Users/alexmorse/.vim/colors/wombat256.vim
/Users/alexmorse/.vim/colors/xoria256.vim
/Users/alexmorse/.vim/ctags/ant.c
/Users/alexmorse/.vim/ctags/argproc.c
/Users/alexmorse/.vim/ctags/args.c
/Users/alexmorse/.vim/ctags/args.h
/Users/alexmorse/.vim/ctags/asm.c
/Users/alexmorse/.vim/ctags/asp.c
/Users/alexmorse/.vim/ctags/awk.c
/Users/alexmorse/.vim/ctags/basic.c
/Users/alexmorse/.vim/ctags/beta.c
/Users/alexmorse/.vim/ctags/c.c
/Users/alexmorse/.vim/ctags/cobol.c
/Users/alexmorse/.vim/ctags/configure.ac
/Users/alexmorse/.vim/ctags/COPYING
/Users/alexmorse/.vim/ctags/ctags.1
/Users/alexmorse/.vim/ctags/ctags.h
/Users/alexmorse/.vim/ctags/ctags.html
/Users/alexmorse/.vim/ctags/ctags.spec
/Users/alexmorse/.vim/ctags/debug.c
/Users/alexmorse/.vim/ctags/debug.h
/Users/alexmorse/.vim/ctags/descrip.mms
/Users/alexmorse/.vim/ctags/dosbatch.c
/Users/alexmorse/.vim/ctags/e_amiga.h
/Users/alexmorse/.vim/ctags/e_djgpp.h
/Users/alexmorse/.vim/ctags/e_mac.h
/Users/alexmorse/.vim/ctags/e_msoft.h
/Users/alexmorse/.vim/ctags/e_os2.h
/Users/alexmorse/.vim/ctags/e_qdos.h
/Users/alexmorse/.vim/ctags/e_riscos.h
/Users/alexmorse/.vim/ctags/e_vms.h
/Users/alexmorse/.vim/ctags/eiffel.c
/Users/alexmorse/.vim/ctags/entry.c
/Users/alexmorse/.vim/ctags/entry.h
/Users/alexmorse/.vim/ctags/erlang.c
/Users/alexmorse/.vim/ctags/EXTENDING.html
/Users/alexmorse/.vim/ctags/FAQ
/Users/alexmorse/.vim/ctags/flex.c
/Users/alexmorse/.vim/ctags/fortran.c
/Users/alexmorse/.vim/ctags/general.h
/Users/alexmorse/.vim/ctags/get.c
/Users/alexmorse/.vim/ctags/get.h
/Users/alexmorse/.vim/ctags/gnu_regex/README.txt
/Users/alexmorse/.vim/ctags/gnu_regex/regcomp.c
/Users/alexmorse/.vim/ctags/gnu_regex/regex.c
/Users/alexmorse/.vim/ctags/gnu_regex/regex.h
/Users/alexmorse/.vim/ctags/gnu_regex/regex_internal.c
/Users/alexmorse/.vim/ctags/gnu_regex/regex_internal.h
/Users/alexmorse/.vim/ctags/gnu_regex/regexec.c
/Users/alexmorse/.vim/ctags/html.c
/Users/alexmorse/.vim/ctags/INSTALL
/Users/alexmorse/.vim/ctags/INSTALL.oth
/Users/alexmorse/.vim/ctags/jscript.c
/Users/alexmorse/.vim/ctags/keyword.c
/Users/alexmorse/.vim/ctags/keyword.h
/Users/alexmorse/.vim/ctags/lisp.c
/Users/alexmorse/.vim/ctags/lregex.c
/Users/alexmorse/.vim/ctags/lua.c
/Users/alexmorse/.vim/ctags/mac.c
/Users/alexmorse/.vim/ctags/magic.diff
/Users/alexmorse/.vim/ctags/main.c
/Users/alexmorse/.vim/ctags/main.h
/Users/alexmorse/.vim/ctags/maintainer.mak
/Users/alexmorse/.vim/ctags/MAINTAINERS
/Users/alexmorse/.vim/ctags/make.c
/Users/alexmorse/.vim/ctags/Makefile
/Users/alexmorse/.vim/ctags/Makefile.in
/Users/alexmorse/.vim/ctags/matlab.c
/Users/alexmorse/.vim/ctags/mk_bc3.mak
/Users/alexmorse/.vim/ctags/mk_bc5.mak
/Users/alexmorse/.vim/ctags/mk_djg.mak
/Users/alexmorse/.vim/ctags/mk_manx.mak
/Users/alexmorse/.vim/ctags/mk_mingw.mak
/Users/alexmorse/.vim/ctags/mk_mpw.mak
/Users/alexmorse/.vim/ctags/mk_mvc.mak
/Users/alexmorse/.vim/ctags/mk_os2.mak
/Users/alexmorse/.vim/ctags/mk_qdos.mak
/Users/alexmorse/.vim/ctags/mk_sas.mak
/Users/alexmorse/.vim/ctags/mkinstalldirs
/Users/alexmorse/.vim/ctags/NEWS
/Users/alexmorse/.vim/ctags/ocaml.c
/Users/alexmorse/.vim/ctags/options.c
/Users/alexmorse/.vim/ctags/options.h
/Users/alexmorse/.vim/ctags/parse.c
/Users/alexmorse/.vim/ctags/parse.h
/Users/alexmorse/.vim/ctags/parsers.h
/Users/alexmorse/.vim/ctags/pascal.c
/Users/alexmorse/.vim/ctags/perl.c
/Users/alexmorse/.vim/ctags/php.c
/Users/alexmorse/.vim/ctags/python.c
/Users/alexmorse/.vim/ctags/qdos.c
/Users/alexmorse/.vim/ctags/read.c
/Users/alexmorse/.vim/ctags/read.h
/Users/alexmorse/.vim/ctags/README
/Users/alexmorse/.vim/ctags/readtags.c
/Users/alexmorse/.vim/ctags/readtags.h
/Users/alexmorse/.vim/ctags/rexx.c
/Users/alexmorse/.vim/ctags/routines.c
/Users/alexmorse/.vim/ctags/routines.h
/Users/alexmorse/.vim/ctags/ruby.c
/Users/alexmorse/.vim/ctags/scheme.c
/Users/alexmorse/.vim/ctags/sh.c
/Users/alexmorse/.vim/ctags/slang.c
/Users/alexmorse/.vim/ctags/sml.c
/Users/alexmorse/.vim/ctags/sort.c
/Users/alexmorse/.vim/ctags/sort.h
/Users/alexmorse/.vim/ctags/source.mak
/Users/alexmorse/.vim/ctags/sql.c
/Users/alexmorse/.vim/ctags/strlist.c
/Users/alexmorse/.vim/ctags/strlist.h
/Users/alexmorse/.vim/ctags/tcl.c
/Users/alexmorse/.vim/ctags/tex.c
/Users/alexmorse/.vim/ctags/verilog.c
/Users/alexmorse/.vim/ctags/vhdl.c
/Users/alexmorse/.vim/ctags/vim.c
/Users/alexmorse/.vim/ctags/vstring.c
/Users/alexmorse/.vim/ctags/vstring.h
/Users/alexmorse/.vim/ctags/yacc.c
/Users/alexmorse/.vim/ctags.conf
/Users/alexmorse/.vim/fonts/ttf-dejavu-powerline/DejaVuSansMono-Bold-Powerline.ttf
/Users/alexmorse/.vim/fonts/ttf-dejavu-powerline/DejaVuSansMono-BoldOblique-Powerline.ttf
/Users/alexmorse/.vim/fonts/ttf-dejavu-powerline/DejaVuSansMono-Oblique-Powerline.ttf
/Users/alexmorse/.vim/fonts/ttf-dejavu-powerline/DejaVuSansMono-Powerline.ttf
/Users/alexmorse/.vim/ftplugin/actionscript.vim
/Users/alexmorse/.vim/ftplugin/css.vim
/Users/alexmorse/.vim/ftplugin/html.vim
/Users/alexmorse/.vim/ftplugin/javascript.vim
/Users/alexmorse/.vim/ftplugin/jinja.vim
/Users/alexmorse/.vim/ftplugin/less.vim
/Users/alexmorse/.vim/ftplugin/python.vim
/Users/alexmorse/.vim/init.sh
/Users/alexmorse/.vim/pycscope-0.3/dwh-cscopeFormat.txt
/Users/alexmorse/.vim/pycscope-0.3/LICENSE
/Users/alexmorse/.vim/pycscope-0.3/MANIFEST.in
/Users/alexmorse/.vim/pycscope-0.3/pycscope.py
/Users/alexmorse/.vim/pycscope-0.3/README
/Users/alexmorse/.vim/pycscope-0.3/replaceNodeType.py
/Users/alexmorse/.vim/pycscope-0.3/runtests.py
/Users/alexmorse/.vim/pycscope-0.3/setup.py
/Users/alexmorse/.vim/pycscope-0.3/test/__init__.py
/Users/alexmorse/.vim/pycscope-0.3/test/issue0018.py
/Users/alexmorse/.vim/pycscope-0.3/test/testissues.py
/Users/alexmorse/.vim/pycscope-0.3/test/testparsesource.py
/Users/alexmorse/.vim/README.md
/Users/alexmorse/.vim/vimrc
